In [3]:
import numpy
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()

# select test indexes
# dataset is ordered so 0, 50, 100 is a first of each kind
test_idx = [0, 50, 100]


# training data
train_target = numpy.delete(iris.target, test_idx)
train_data = numpy.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

# create and train classifier
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)


print(test_target)
# Output: [0 1 2]

output = clf.predict(test_data)
print(output)
# Output: [0 1 2]


print(test_data[0], test_target[0])
# output: [ 5.1  3.5  1.4  0.2] 0


print(iris.feature_names)
# output: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

print(iris.target_names)
# output: ['setosa' 'versicolor' 'virginica']


# Vizualization of Decision Tree Classifier
from sklearn.externals.six import StringIO
import pydotplus

dot_data = StringIO()
tree.export_graphviz(
    decision_tree=clf,
    out_file=dot_data,
    feature_names=iris.feature_names,
    class_names=iris.target_names,
    filled=True,
    rounded=True,
    impurity=True
)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf('/tmp/iris.pdf')

[0 1 2]
[0 1 2]
[ 5.1  3.5  1.4  0.2] 0
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


True